apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-deployment-demo
  labels:
    app: my-deployment-demo
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
      - image: sjc.vultrcr.com/workshopton/backend-mock:latest
        name: backend-mock
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-deployment
  name: my-deployment
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    name: http
  selector:
    app: my-deployment
  type: ClusterIP

---
 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-deployment
  annotations:
    cert-manager.io/issuer: "cloudflare-letsencrypt"
spec:
  ingressClassName: nginx
  rules:
  - host: teste.diadecloud.com
    http:
      paths:
      - backend:
          service:
            name: my-deployment
            port:
              number: 80
        path: /
        pathType: Prefix