name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: https://sjc.vultrcr.com/workshopton
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker compose build
          docker compose push sjc.vultrcr.com/workshopton/meu-servico:latest
